test(python): improve bindings test to detect ABI incompatibilities
Previously, python bindings test would not detect ABI incompatibilities.
At this time, the latest pypi release of py-tree-sitter does not support
15, which is the default, and it creates the problem.

Improve the test to create a Parser, which will detect it:
```
======================================================================
ERROR: test_can_load_grammar
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../tests/test_binding.py", line 10, in test_can_load_grammar
    _ = Parser(language)
ValueError: Incompatible Language version 15. Must be between 13 and 14

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```