fix(endian): avoid <sys/byteorder.h> in __sun branch
The __sun branch added in 77cb23fc defines byte order conversions in terms of
BE_16/LE_16 from <sys/byteorder.h>. These macros sit behind:

  #if !defined(_XPG4_2) || defined(__EXTENSIONS__)

This breaks during link time because lib/binding_rust/build.rs defines
_POSIX_C_SOURCE=200112L, which sys/feature_tests.h converts to _XPG4_2.
This means the BE_16/LE_16 macros are undefined, resulting in a link-time
failure:

error: linking with `x86_64-unknown-illumos-gcc` failed: exit status: 1
  = note: /usr/local/x86_64-unknown-illumos/lib/gcc/x86_64-pc-solaris2.10/8.4.0/../../../../x86_64-pc-solaris2.10/bin/ld: warning: -z ignore ignored.
          /target/x86_64-unknown-illumos/release-lto/deps/rustcX/libtree_sitter-xxx.rlib(xxx-lib.o): In function `ts_decode_utf16_le':
          lib.c:(.text.ts_decode_utf16_le+0x21): undefined reference to `LE_16'
          /target/x86_64-unknown-illumos/release-lto/deps/rustcX/libtree_sitter-xxx.rlib(xxx-lib.o): In function `ts_decode_utf16_be':
          lib.c:(.text.ts_decode_utf16_be+0x21): undefined reference to `BE_16'
          collect2: error: ld returned 1 exit status

The reason this didn't show up in CI is because it's not triggered
during the build of a static library, only at the final linking step.

To be consistent w/ the other platforms in this file, this change adopts
__builtin_bswap* and no longer relies on external system headers.