lib: build: Add meson build system support
This makes building, installing, and using the tree-sitter library much simpler and faster.

 * meson.build: Top level meson project. Currently only handles building the tree-sitter C library
 * lib/meson.build: meson tree-sitter library definition
 * lib/include/meson.build: meson tree-sitter library public header definitions
 * lib/src/meson.build: meson tree-sitter library source definitions
 * lib/src/query.c: fix missing include resulting in undefined reference to `ts_decode_utf8`